version: '3.8'

services:
  postgres:
    container_name: jobber-postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - jobber-network

networks:
  jobber-network:
    driver: bridge
